
export const productData = [
  {
    id: 1,
    name: "MacBook Air M4",
    brand: "Apple",
    price: "₹1,19,900",
    originalPrice: "₹1,29,900",
    rating: 4.9,
    reviews: 245,
    aiScore: 98,
    badge: "AI Pick",
    image: "/src/public/images/hero/macbook.png",
    inStock: true,
  },
  {
    id: 2,
    name: "Sony WH-1000XM6",
    brand: "Sony",
    price: "₹29,990",
    originalPrice: "₹34,990",
    rating: 4.8,
    reviews: 187,
    aiScore: 97,
    badge: "Best Audio",
    image: "/src/public/images/hero/sony.png",
    inStock: true,
  },
  {
    id: 3,
    name: "Nike Air Max",
    brand: "Nike",
    price: "₹10,499",
    originalPrice: "₹12,999",
    rating: 4.7,
    reviews: 152,
    aiScore: 95,
    badge: "Trending",
    image: "/src/public/images/hero/nike.png",
    inStock: true,
  },
  {
    id: 4,
    name: "iPhone 17 Pro",
    brand: "Apple",
    price: "₹1,29,999",
    originalPrice: "₹1,39,999",
    rating: 4.9,
    reviews: 320,
    aiScore: 99,
    badge: "Editor's Choice",
    image: "/src/public/images/hero/iphone.png",
    inStock: true,
  },
];